add_magnet:
  fields:
    magnet:
      required: true
      example: "magnet:?xt=urn:btih:..."
      selector:
        text:

    category:
      required: false
      selector:
        text:

    clean_title:
      required: false
      selector:
        text:

    rename_name:
      required: false
      selector:
        text:

    token_type:
      required: false
      selector:
        text:

    season:
      required: false
      selector:
        text:

    res:
      required: false
      selector:
        text:

    codec:
      required: false
      selector:
        text:

    audio:
      required: false
      selector:
        text: